# Generated by Django 2.2.28 on 2022-11-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221128_1853'),
        ('posts', '0004_auto_20221126_2010'),
    ]

    operations = [
    ]
